name: 04 - CD Prod (SFTP)

on:
  push:
    branches: [ "main", "master" ] # Uniquement sur la prod

jobs:
  deploy-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Transfert des fichiers de production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local-dir: ./
          server-dir: /var/www/ecoshop/